project:
  type: book
  output-dir: ../docs

book:
  title: "book"
  author: "Jane Doe"
  date: "28-3-2023"
  chapters:
    - index.qmd
    - intro.qmd
    - i-analyzer.qmd
    - base-r.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: pulse




