project:
  type: book
  output-dir: ../docs

book:
  title: "Text Mining with I-Analyzer & R"
  author: "Research Data Management Support"
  date: "04-25-2023"
  chapters:
    - index.qmd
    - syllabus.qmd
    - course-outline-and-schedule.qmd
    - part: "1 I-Analyzer"
      chapters:
      - ianalyzer-preparation.qmd
      - ianalyzer-session.qmd
      - ianalyzer-homework.qmd
    - part: "2 Base R" 
      chapters:
      - r-preparation.qmd
      - r-session.qmd
      - r-homework.qmd
    - part: "3 Guest Lecture & Literature Review"
      chapters:
      - lecture-and-literature-preparation.qmd
      - lecture-and-literature-session.qmd
      - lecture-and-literature-homework.qmd
    - part: "4 Tidy Text Mining"
      chapters:
      - text-mining-preparation.qmd
      - text_mining_with_R.qmd
      - text-mining-homework.qmd
    - part: "5 Reproducible Reports"
      chapters:
      - reproducible-reports-preparation.qmd
      - reproducible-reports-session.qmd
    - final-assignment.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: pulse




