# Homework {.unnumbered}

As homework, you are required to:

**1. Complete the Base R exercises conducted during the session.**

This is if you didn't already finish it during the meeting. Use the videos and slides as a reference for completing the exercises.

Note that you will be required to submit the completed exercises: [baseR_exercises.Rmd](https://utrechtuniversity.github.io/workshop-introduction-to-R-and-data/baseR_exercises.Rmd), as part of the grading of the course.

If you get stuck, don't hesitate to reach out to the instructors during the [Walk-In Hours of Research Data Management Support](https://www.uu.nl/en/research/research-data-management/walk-in-hours-workshops/walk-in-hours-research-data-software). The Walk-In Hours take place every Monday from 15:00 to 17:00 at the University Library in the Science Park. However, one instructor will be available at the University Library in the city center (in the seating area near the Digital Humanities Lab) and you are welcome free to request a meeting online (via MS Teams) during these hours as well.

_**Don't forget the preparation for the next session!**_