---
title: "test_idf"
output: html_document
date: "2023-04-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
library(tidytext)
library(dplyr)
```

```{r}
data_file_name <- '../data/times_ocr=80_100&date=1945-01-01_2010-12-31&query=_european_union_&category=News.csv'
data_df <- read_delim(data_file_name, delim = ";", escape_double = FALSE, col_types = cols(`date-pub` = col_date(format = "%B %d, %Y")), trim_ws = TRUE)
```

```{r}
issues <- data_df$issue
any(is.na(issues))
print(sum(any(is.na(issues))))
```

```{r}
library(naniar)
gg_miss_var(data_df)
gg_miss_upset(data_df)
```

```{r}
issue_words <- data_df %>%
  unnest_tokens(word, content) %>%
  count(issue, word, sort = TRUE)

any(is.na(issue_words))
issue_words[!complete.cases(issue_words), ]
```

```{r}
issue_words <- na.omit(issue_words)

issue_tf_idf <- issue_words %>%
  bind_tf_idf(word, issue, n)

issue_tf_idf %>%
  arrange(tf_idf)
```


```{r}
print(nrow(data_df %>% distinct(issue)))
print(length(tapply(issue_words$n, issue_words$issue, sum)))
test2 <- issue_words %>% group_by(issue) %>% summarize(mean_value = mean(n))
print(nrow(test2))
```


```{r}
bind_tf_idf2 <- function(tbl, term, document, n) {
  term <- quo_name(enquo(term))
  document <- quo_name(enquo(document))
  n_col <- quo_name(enquo(n))

  terms <- as.character(tbl[[term]])
  documents <- as.character(tbl[[document]])
  n <- tbl[[n_col]]
  doc_totals <- tapply(n, documents, sum)
  idf <- log(length(doc_totals) / table(terms))

  tbl$tf <- n / as.numeric(doc_totals[documents])
  tbl$idf <- as.numeric(idf[terms])
  tbl$tf_idf <- tbl$tf * tbl$idf

  if(any(tbl$idf < 0, na.rm = TRUE)) {
    rlang::warn(paste("A value for tf_idf is negative:\n",
                      "Input should have exactly one row per document-term combination."))
  }
  tbl
}
```
```{r}
issue_words_the <- data_df %>%
  unnest_tokens(word, content) %>%
  filter(word=="the") %>%
  count(issue, word, sort = TRUE)

print(any(is.na(issue_words_the$issue)))
print(which(is.na(issue_words_the$issue)))
print(nrow(issue_words_the %>% na.omit() %>% distinct(issue)))

issue_tf_idf_the <- issue_words_the %>%
  bind_tf_idf(word, issue, n)

issue_tf_idf_the 
```

```{r}
total_words <- issue_words %>% 
  group_by(issue) %>% 
  summarize(total = sum(n))

issue_total_words <- left_join(issue_words, total_words) %>% arrange(desc(issue)) %>% 
  filter(word=="the")

row_index <- which.max(issue_total_words$n)
print(row_index)
print(issue_total_words[row_index,])
issue_sel <- 56145
print(nrow(data_df %>% distinct(issue)))
print(nrow(issue_total_words %>% filter(word=="the")))
print(typeof(issue_words$n))
```

```{r}
print(log(1305/1305))
```


```{r}
doc_totals <- tapply(issue_words$n, issue_words$issue, sum)

n_terms = table(issue_words$word)
n_issues = length(doc_totals)
idf <- log(n_issues / n_terms)
neg_rows <- idf[idf < 0 ]

print(nrow(issue_words %>% distinct(issue)))
print(max(n_terms))
print(max(n_issues))

print(neg_rows)

words <- as.character(issue_words[['word']])
issue_words$idf <- as.numeric(idf[issue_words$words])
```

```{r}
test <- issue_words[grepl("the", issue_words$word), ] %>%
  arrange(issue)
test2 <- issue_words[grepl("the", issue_words$word), ] %>%
  arrange(issue) %>% distinct(issue)

test

print(nrow(test))
print(nrow(test2))
```
